// Code generated by mojo. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: cat/v1/cats.proto

package cat

import (
	cat "github.com/liankui/tnr/go/pkg/cat"
	core "github.com/mojo-lang/core/go/pkg/mojo/core"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cat *cat.Cat `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
}

func (x *CreateCatRequest) Reset() {
	*x = CreateCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_v1_cats_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCatRequest) ProtoMessage() {}

func (x *CreateCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cats_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCatRequest.ProtoReflect.Descriptor instead.
func (*CreateCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cats_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCatRequest) GetCat() *cat.Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

type UpdateCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cat *cat.Cat `protobuf:"bytes,1,opt,name=cat,proto3" json:"cat,omitempty"`
}

func (x *UpdateCatRequest) Reset() {
	*x = UpdateCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_v1_cats_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCatRequest) ProtoMessage() {}

func (x *UpdateCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cats_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCatRequest.ProtoReflect.Descriptor instead.
func (*UpdateCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cats_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateCatRequest) GetCat() *cat.Cat {
	if x != nil {
		return x.Cat
	}
	return nil
}

type GetCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCatRequest) Reset() {
	*x = GetCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_v1_cats_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatRequest) ProtoMessage() {}

func (x *GetCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cats_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatRequest.ProtoReflect.Descriptor instead.
func (*GetCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cats_proto_rawDescGZIP(), []int{2}
}

func (x *GetCatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize  int32  `protobuf:"varint,2000,opt,name=page_size,json=pageSize,proto3" json:"pageSize,omitempty"`
	PageToken string `protobuf:"bytes,2001,opt,name=page_token,json=pageToken,proto3" json:"pageToken,omitempty"`
	Skip      int32  `protobuf:"varint,2002,opt,name=skip,proto3" json:"skip,omitempty"`
}

func (x *ListCatsRequest) Reset() {
	*x = ListCatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_v1_cats_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatsRequest) ProtoMessage() {}

func (x *ListCatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cats_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatsRequest.ProtoReflect.Descriptor instead.
func (*ListCatsRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cats_proto_rawDescGZIP(), []int{3}
}

func (x *ListCatsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCatsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListCatsRequest) GetSkip() int32 {
	if x != nil {
		return x.Skip
	}
	return 0
}

type ListCatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cats          []*cat.Cat `protobuf:"bytes,1,rep,name=cats,proto3" json:"cats,omitempty"`
	TotalCount    int32      `protobuf:"varint,2000,opt,name=total_count,json=totalCount,proto3" json:"totalCount,omitempty"`
	NextPageToken string     `protobuf:"bytes,2001,opt,name=next_page_token,json=nextPageToken,proto3" json:"nextPageToken,omitempty"`
}

func (x *ListCatsResponse) Reset() {
	*x = ListCatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_v1_cats_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatsResponse) ProtoMessage() {}

func (x *ListCatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cats_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatsResponse.ProtoReflect.Descriptor instead.
func (*ListCatsResponse) Descriptor() ([]byte, []int) {
	return file_cat_v1_cats_proto_rawDescGZIP(), []int{4}
}

func (x *ListCatsResponse) GetCats() []*cat.Cat {
	if x != nil {
		return x.Cats
	}
	return nil
}

func (x *ListCatsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListCatsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type BatchGetCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *BatchGetCatRequest) Reset() {
	*x = BatchGetCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_v1_cats_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetCatRequest) ProtoMessage() {}

func (x *BatchGetCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cats_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetCatRequest.ProtoReflect.Descriptor instead.
func (*BatchGetCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cats_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetCatRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchGetCatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cats []*cat.Cat `protobuf:"bytes,1,rep,name=cats,proto3" json:"cats,omitempty"`
}

func (x *BatchGetCatResponse) Reset() {
	*x = BatchGetCatResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_v1_cats_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchGetCatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetCatResponse) ProtoMessage() {}

func (x *BatchGetCatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cats_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetCatResponse.ProtoReflect.Descriptor instead.
func (*BatchGetCatResponse) Descriptor() ([]byte, []int) {
	return file_cat_v1_cats_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetCatResponse) GetCats() []*cat.Cat {
	if x != nil {
		return x.Cats
	}
	return nil
}

type DeleteCatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCatRequest) Reset() {
	*x = DeleteCatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_v1_cats_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCatRequest) ProtoMessage() {}

func (x *DeleteCatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cat_v1_cats_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCatRequest.ProtoReflect.Descriptor instead.
func (*DeleteCatRequest) Descriptor() ([]byte, []int) {
	return file_cat_v1_cats_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_cat_v1_cats_proto protoreflect.FileDescriptor

var file_cat_v1_cats_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x61, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x0d, 0x63, 0x61, 0x74,
	0x2f, 0x63, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x6d, 0x6f, 0x6a, 0x6f,
	0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x6e, 0x75, 0x6c, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x2e, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x52, 0x03, 0x63, 0x61, 0x74,
	0x22, 0x2e, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x03, 0x63, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x52, 0x03, 0x63, 0x61, 0x74,
	0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x64, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0xd0, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69,
	0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0xd1, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x13, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x18, 0xd2, 0x0f, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x70, 0x22, 0x7b, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x63,
	0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e,
	0x43, 0x61, 0x74, 0x52, 0x04, 0x63, 0x61, 0x74, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0xd0, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x6e,
	0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0xd1,
	0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x26, 0x0a, 0x12, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x33, 0x0a, 0x13,
	0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x63, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x52, 0x04, 0x63, 0x61, 0x74,
	0x73, 0x22, 0x22, 0x0a, 0x10, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xd9, 0x02, 0x0a, 0x04, 0x43, 0x61, 0x74, 0x73, 0x12, 0x30,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x12, 0x18, 0x2e, 0x63,
	0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74,
	0x12, 0x30, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x12, 0x18,
	0x2e, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43,
	0x61, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x12, 0x15, 0x2e,
	0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x43, 0x61, 0x74, 0x12, 0x3e,
	0x0a, 0x09, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x73, 0x12, 0x17, 0x2e, 0x63, 0x61,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48,
	0x0a, 0x0d, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x61, 0x74, 0x12,
	0x1a, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65,
	0x74, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x61,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x47, 0x65, 0x74, 0x43, 0x61, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x5f, 0x63, 0x61, 0x74, 0x12, 0x18, 0x2e, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0f, 0x2e, 0x6d, 0x6f, 0x6a, 0x6f, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x4e, 0x75, 0x6c,
	0x6c, 0x42, 0x4b, 0x0a, 0x12, 0x63, 0x6f, 0x6d, 0x2e, 0x6c, 0x69, 0x61, 0x6e, 0x6b, 0x75, 0x69,
	0x2e, 0x63, 0x61, 0x74, 0x2e, 0x76, 0x31, 0x42, 0x09, 0x43, 0x61, 0x74, 0x73, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6b, 0x75, 0x69, 0x2f, 0x74, 0x6e, 0x72, 0x2f, 0x67, 0x6f, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x63, 0x61, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cat_v1_cats_proto_rawDescOnce sync.Once
	file_cat_v1_cats_proto_rawDescData = file_cat_v1_cats_proto_rawDesc
)

func file_cat_v1_cats_proto_rawDescGZIP() []byte {
	file_cat_v1_cats_proto_rawDescOnce.Do(func() {
		file_cat_v1_cats_proto_rawDescData = protoimpl.X.CompressGZIP(file_cat_v1_cats_proto_rawDescData)
	})
	return file_cat_v1_cats_proto_rawDescData
}

var file_cat_v1_cats_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cat_v1_cats_proto_goTypes = []interface{}{
	(*CreateCatRequest)(nil),    // 0: cat.v1.CreateCatRequest
	(*UpdateCatRequest)(nil),    // 1: cat.v1.UpdateCatRequest
	(*GetCatRequest)(nil),       // 2: cat.v1.GetCatRequest
	(*ListCatsRequest)(nil),     // 3: cat.v1.ListCatsRequest
	(*ListCatsResponse)(nil),    // 4: cat.v1.ListCatsResponse
	(*BatchGetCatRequest)(nil),  // 5: cat.v1.BatchGetCatRequest
	(*BatchGetCatResponse)(nil), // 6: cat.v1.BatchGetCatResponse
	(*DeleteCatRequest)(nil),    // 7: cat.v1.DeleteCatRequest
	(*cat.Cat)(nil),             // 8: cat.Cat
	(*core.Null)(nil),           // 9: mojo.core.Null
}
var file_cat_v1_cats_proto_depIdxs = []int32{
	8,  // 0: cat.v1.CreateCatRequest.cat:type_name -> cat.Cat
	8,  // 1: cat.v1.UpdateCatRequest.cat:type_name -> cat.Cat
	8,  // 2: cat.v1.ListCatsResponse.cats:type_name -> cat.Cat
	8,  // 3: cat.v1.BatchGetCatResponse.cats:type_name -> cat.Cat
	0,  // 4: cat.v1.Cats.create_cat:input_type -> cat.v1.CreateCatRequest
	1,  // 5: cat.v1.Cats.update_cat:input_type -> cat.v1.UpdateCatRequest
	2,  // 6: cat.v1.Cats.get_cat:input_type -> cat.v1.GetCatRequest
	3,  // 7: cat.v1.Cats.list_cats:input_type -> cat.v1.ListCatsRequest
	5,  // 8: cat.v1.Cats.batch_get_cat:input_type -> cat.v1.BatchGetCatRequest
	7,  // 9: cat.v1.Cats.delete_cat:input_type -> cat.v1.DeleteCatRequest
	8,  // 10: cat.v1.Cats.create_cat:output_type -> cat.Cat
	8,  // 11: cat.v1.Cats.update_cat:output_type -> cat.Cat
	8,  // 12: cat.v1.Cats.get_cat:output_type -> cat.Cat
	4,  // 13: cat.v1.Cats.list_cats:output_type -> cat.v1.ListCatsResponse
	6,  // 14: cat.v1.Cats.batch_get_cat:output_type -> cat.v1.BatchGetCatResponse
	9,  // 15: cat.v1.Cats.delete_cat:output_type -> mojo.core.Null
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_cat_v1_cats_proto_init() }
func file_cat_v1_cats_proto_init() {
	if File_cat_v1_cats_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cat_v1_cats_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_v1_cats_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_v1_cats_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_v1_cats_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_v1_cats_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_v1_cats_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_v1_cats_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchGetCatResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cat_v1_cats_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cat_v1_cats_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cat_v1_cats_proto_goTypes,
		DependencyIndexes: file_cat_v1_cats_proto_depIdxs,
		MessageInfos:      file_cat_v1_cats_proto_msgTypes,
	}.Build()
	File_cat_v1_cats_proto = out.File
	file_cat_v1_cats_proto_rawDesc = nil
	file_cat_v1_cats_proto_goTypes = nil
	file_cat_v1_cats_proto_depIdxs = nil
}
