// Code generated by mojo. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: cat/family_tree.proto

package cat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FamilyTree struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId    string   `protobuf:"bytes,1,opt,name=cat_id,json=catId,proto3" json:"catId,omitempty"`
	Name     string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NickName string   `protobuf:"bytes,3,opt,name=nick_name,json=nickName,proto3" json:"nickName,omitempty"`
	Sex      string   `protobuf:"bytes,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Ancestor []string `protobuf:"bytes,10,rep,name=ancestor,proto3" json:"ancestor,omitempty"`
	Parent   []string `protobuf:"bytes,20,rep,name=parent,proto3" json:"parent,omitempty"`
	Spouse   []string `protobuf:"bytes,25,rep,name=spouse,proto3" json:"spouse,omitempty"`
	Child    []string `protobuf:"bytes,30,rep,name=child,proto3" json:"child,omitempty"`
}

func (x *FamilyTree) Reset() {
	*x = FamilyTree{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cat_family_tree_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FamilyTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FamilyTree) ProtoMessage() {}

func (x *FamilyTree) ProtoReflect() protoreflect.Message {
	mi := &file_cat_family_tree_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FamilyTree.ProtoReflect.Descriptor instead.
func (*FamilyTree) Descriptor() ([]byte, []int) {
	return file_cat_family_tree_proto_rawDescGZIP(), []int{0}
}

func (x *FamilyTree) GetCatId() string {
	if x != nil {
		return x.CatId
	}
	return ""
}

func (x *FamilyTree) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FamilyTree) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *FamilyTree) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *FamilyTree) GetAncestor() []string {
	if x != nil {
		return x.Ancestor
	}
	return nil
}

func (x *FamilyTree) GetParent() []string {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *FamilyTree) GetSpouse() []string {
	if x != nil {
		return x.Spouse
	}
	return nil
}

func (x *FamilyTree) GetChild() []string {
	if x != nil {
		return x.Child
	}
	return nil
}

var File_cat_family_tree_proto protoreflect.FileDescriptor

var file_cat_family_tree_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x61, 0x74, 0x2f, 0x66, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x5f, 0x74, 0x72, 0x65,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x61, 0x74, 0x22, 0xc8, 0x01, 0x0a,
	0x0a, 0x46, 0x61, 0x6d, 0x69, 0x6c, 0x79, 0x54, 0x72, 0x65, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x63,
	0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18, 0x14, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70, 0x6f,
	0x75, 0x73, 0x65, 0x18, 0x19, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x70, 0x6f, 0x75, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x18, 0x1e, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x42, 0x4b, 0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x6c,
	0x69, 0x61, 0x6e, 0x6b, 0x75, 0x69, 0x2e, 0x63, 0x61, 0x74, 0x42, 0x0f, 0x46, 0x61, 0x6d, 0x69,
	0x6c, 0x79, 0x54, 0x72, 0x65, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x25, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x61, 0x6e, 0x6b, 0x75,
	0x69, 0x2f, 0x74, 0x6e, 0x72, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x61, 0x74,
	0x3b, 0x63, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cat_family_tree_proto_rawDescOnce sync.Once
	file_cat_family_tree_proto_rawDescData = file_cat_family_tree_proto_rawDesc
)

func file_cat_family_tree_proto_rawDescGZIP() []byte {
	file_cat_family_tree_proto_rawDescOnce.Do(func() {
		file_cat_family_tree_proto_rawDescData = protoimpl.X.CompressGZIP(file_cat_family_tree_proto_rawDescData)
	})
	return file_cat_family_tree_proto_rawDescData
}

var file_cat_family_tree_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_cat_family_tree_proto_goTypes = []interface{}{
	(*FamilyTree)(nil), // 0: cat.FamilyTree
}
var file_cat_family_tree_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cat_family_tree_proto_init() }
func file_cat_family_tree_proto_init() {
	if File_cat_family_tree_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cat_family_tree_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FamilyTree); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cat_family_tree_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cat_family_tree_proto_goTypes,
		DependencyIndexes: file_cat_family_tree_proto_depIdxs,
		MessageInfos:      file_cat_family_tree_proto_msgTypes,
	}.Build()
	File_cat_family_tree_proto = out.File
	file_cat_family_tree_proto_rawDesc = nil
	file_cat_family_tree_proto_goTypes = nil
	file_cat_family_tree_proto_depIdxs = nil
}
