logs:
  level: debug
  encode: console # json or console
  # output: file
  initFields:
    package: cat.v1
    server: cats-server
    version: 1.0
  file:
    path: ./logs/app.log
    maxSize: 100
    maxBackups: 10
    maxAge: 28
    encode: console
    # Compress: false
